version: 2
jobs:
  build_v10: &build
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: node bin/cli.js init

      - run: node bin/cli.js create test-migration

      - run: node bin/cli.js migrate

      # And again to make sure it doesnt crash when queue is empty
      - run: node bin/cli.js migrate

      # Test backwards-compatible alias
      # TODO: Remove in ^2.0.0
      - run: node bin/cli.js run

  build_v12:
    <<: *build
    docker:
      - image: circleci/node:12

  build_v14:
    <<: *build
    docker:
      - image: circleci/node:14

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_v10
      - build_v12
      - build_v14
